# golangci-lint configuration
run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    # Essential linters
    - errcheck         # Check for unchecked errors
    - gosimple         # Simplify code
    - govet            # Vet examines Go source code
    - ineffassign      # Detect ineffectual assignments
    - staticcheck      # Static analysis
    - unused           # Check for unused constants, variables, functions, types, fields
    - gofmt            # Format code
    - misspell         # Find misspelled English words
    - unparam          # Report unused function parameters

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/biwakonbu/agent-runner

  misspell:
    locale: US

issues:
  exclude-use-default: false
  exclude:
    # Allow fmt.Printf in tests
    - "fmt.Printf"
  exclude-rules:
    # Ignore errors in tests
    - path: "_test\\.go"
      linters:
        - errcheck
        - unparam
