// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateChatSession() {
  return window['go']['main']['App']['CreateChatSession']();
}

export function CreateTask(arg1, arg2) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2);
}

export function DeleteBacklogItem(arg1) {
  return window['go']['main']['App']['DeleteBacklogItem'](arg1);
}

export function GetAllBacklogItems() {
  return window['go']['main']['App']['GetAllBacklogItems']();
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetAvailablePools() {
  return window['go']['main']['App']['GetAvailablePools']();
}

export function GetAvailableTools() {
  return window['go']['main']['App']['GetAvailableTools']();
}

export function GetBacklogItems() {
  return window['go']['main']['App']['GetBacklogItems']();
}

export function GetChatHistory(arg1) {
  return window['go']['main']['App']['GetChatHistory'](arg1);
}

export function GetExecutionState() {
  return window['go']['main']['App']['GetExecutionState']();
}

export function GetLLMConfig() {
  return window['go']['main']['App']['GetLLMConfig']();
}

export function GetModelsForTool(arg1) {
  return window['go']['main']['App']['GetModelsForTool'](arg1);
}

export function GetPoolSummaries() {
  return window['go']['main']['App']['GetPoolSummaries']();
}

export function GetToolingConfigJSON() {
  return window['go']['main']['App']['GetToolingConfigJSON']();
}

export function GetWorkspace(arg1) {
  return window['go']['main']['App']['GetWorkspace'](arg1);
}

export function ListAttempts(arg1) {
  return window['go']['main']['App']['ListAttempts'](arg1);
}

export function ListRecentWorkspaces() {
  return window['go']['main']['App']['ListRecentWorkspaces']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function OpenWorkspaceByID(arg1) {
  return window['go']['main']['App']['OpenWorkspaceByID'](arg1);
}

export function PauseExecution() {
  return window['go']['main']['App']['PauseExecution']();
}

export function RemoveWorkspace(arg1) {
  return window['go']['main']['App']['RemoveWorkspace'](arg1);
}

export function ResolveBacklogItem(arg1, arg2) {
  return window['go']['main']['App']['ResolveBacklogItem'](arg1, arg2);
}

export function ResumeExecution() {
  return window['go']['main']['App']['ResumeExecution']();
}

export function RunTask(arg1) {
  return window['go']['main']['App']['RunTask'](arg1);
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}

export function SendChatMessage(arg1, arg2) {
  return window['go']['main']['App']['SendChatMessage'](arg1, arg2);
}

export function SetLLMConfig(arg1) {
  return window['go']['main']['App']['SetLLMConfig'](arg1);
}

export function SetToolingConfigJSON(arg1) {
  return window['go']['main']['App']['SetToolingConfigJSON'](arg1);
}

export function StartExecution() {
  return window['go']['main']['App']['StartExecution']();
}

export function StopExecution() {
  return window['go']['main']['App']['StopExecution']();
}

export function TestLLMConnection() {
  return window['go']['main']['App']['TestLLMConnection']();
}

export function ValidateToolModelCombination(arg1, arg2) {
  return window['go']['main']['App']['ValidateToolModelCombination'](arg1, arg2);
}
