// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1, arg2) {
  return window['go']['main']['App']['CreateTask'](arg1, arg2);
}

export function GetPoolSummaries() {
  return window['go']['main']['App']['GetPoolSummaries']();
}

export function GetWorkspace(arg1) {
  return window['go']['main']['App']['GetWorkspace'](arg1);
}

export function ListAttempts(arg1) {
  return window['go']['main']['App']['ListAttempts'](arg1);
}

export function ListRecentWorkspaces() {
  return window['go']['main']['App']['ListRecentWorkspaces']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function OpenWorkspaceByID(arg1) {
  return window['go']['main']['App']['OpenWorkspaceByID'](arg1);
}

export function RemoveWorkspace(arg1) {
  return window['go']['main']['App']['RemoveWorkspace'](arg1);
}

export function RunTask(arg1) {
  return window['go']['main']['App']['RunTask'](arg1);
}

export function SelectWorkspace() {
  return window['go']['main']['App']['SelectWorkspace']();
}
