// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {chat} from '../models';
import {orchestrator} from '../models';
import {main} from '../models';
import {ide} from '../models';

export function CreateChatSession():Promise<chat.ChatSession>;

export function CreateTask(arg1:string,arg2:string):Promise<orchestrator.Task>;

export function DeleteBacklogItem(arg1:string):Promise<void>;

export function GetAllBacklogItems():Promise<Array<orchestrator.BacklogItem>>;

export function GetAvailablePools():Promise<Array<orchestrator.Pool>>;

export function GetBacklogItems():Promise<Array<orchestrator.BacklogItem>>;

export function GetChatHistory(arg1:string):Promise<Array<chat.ChatMessage>>;

export function GetExecutionState():Promise<string>;

export function GetLLMConfig():Promise<main.LLMConfigDTO>;

export function GetPoolSummaries():Promise<Array<orchestrator.PoolSummary>>;

export function GetToolingConfigJSON():Promise<string>;

export function GetWorkspace(arg1:string):Promise<ide.Workspace>;

export function ListAttempts(arg1:string):Promise<Array<orchestrator.Attempt>>;

export function ListRecentWorkspaces():Promise<Array<ide.WorkspaceSummary>>;

export function ListTasks():Promise<Array<orchestrator.Task>>;

export function OpenWorkspaceByID(arg1:string):Promise<string>;

export function PauseExecution():Promise<void>;

export function RemoveWorkspace(arg1:string):Promise<void>;

export function ResolveBacklogItem(arg1:string,arg2:string):Promise<void>;

export function ResumeExecution():Promise<void>;

export function RunTask(arg1:string):Promise<void>;

export function SelectWorkspace():Promise<string>;

export function SendChatMessage(arg1:string,arg2:string):Promise<main.ChatResponseDTO>;

export function SetLLMConfig(arg1:main.LLMConfigDTO):Promise<void>;

export function SetToolingConfigJSON(arg1:string):Promise<void>;

export function StartExecution():Promise<void>;

export function StopExecution():Promise<void>;

export function TestLLMConnection():Promise<string>;
