// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {ide} from '../models';
import {orchestrator} from '../models';

export function CreateTask(arg1:string,arg2:string):Promise<orchestrator.Task>;

export function GetPoolSummaries():Promise<Array<orchestrator.PoolSummary>>;

export function GetWorkspace(arg1:string):Promise<ide.Workspace>;

export function ListAttempts(arg1:string):Promise<Array<orchestrator.Attempt>>;

export function ListRecentWorkspaces():Promise<Array<ide.WorkspaceSummary>>;

export function ListTasks():Promise<Array<orchestrator.Task>>;

export function OpenWorkspaceByID(arg1:string):Promise<string>;

export function RemoveWorkspace(arg1:string):Promise<void>;

export function RunTask(arg1:string):Promise<void>;

export function SelectWorkspace():Promise<string>;

export function GetAvailablePools():Promise<Array<{id: string, name: string, description?: string}>>;
